---
title: "Course Introduction"
subtitle: "30208 - Emotions and social stratification"
author: "Philipp Wunderlich"
date: "2023"
format: revealjs
editor: visual
embed-resources: true
---

# Introduction

-   Topic: What are emotions? How are they stratified? Why is this relevant?

-   Interest & learning goals

-   Course plan, requirements, tasks

-   Seminar paper

# Emotions in sociology

## Emotions

> „(...) emotions constitute the bodily manifestation of the importance that an event in the natural or social world has for a subject." (Bericat, 2016, p. 493)

. . .

-   *Appraisals* of situations or objects

-   *Relational* nature

-   Feeling, subjective *experience* & *embodiment*

-   Action tendencies & *motivations*

-   ➔ Emotions are social, social life is emotional

## Sociology of emotions

-   Emotion cultures, norms, rules

-   Social constructionist perspectives on emotions

-   Intergroup, collective emotions

-   Emotions in social interaction and ritual encounters

-   Structural accounts, power and status

## Examples

-   Anger and indignation as drivers of social movements and protest.

-   Shame and pride as emotions of social control (e.g. flight shame).

-   Deep acting of emotions in service professions

-   Emotional dynamics underlying right-wing populism

# This seminar

## Interest

-   What are you expecting from the course? What is your *personal* interest (previous studies etc.)?

-   How are emotions related to dimensions of inequality such as class, gender, race, age or education?

## Learning goals

-   Explore the research field of emotional stratification, a sub-field of the sociology of emotions

-   *Focus on writing*: How to author papers and provide feedback.

-   What we WON'T focus on:

    -   Applied quantitative socio-structural analysis.

    -   Country comparisons

    -   *Comprehensive* explanations of social inequalities

# Requirements

-   Regular participation

-   Active participation

    -   Mandatory reading and reading responses

    -   Submission tasks

-   Module exam (Seminar paper)

## Regular participation

-   You may miss up to 2 sessions without a doctor's note.

-   I will not control your presence regularly, but:

-   You have to attend regularly, to be able to fulfill active participation

## Active participation

-   Questions and Reading responses have to be uploaded each Friday (noon).

    -   Miss no more than 2.

-   Submission of research question (31.5.2023)

-   Submission of first draft (5.7.2023)

## Seminar paper

-   Either seminar paper or oral exam.

    -   Seminar paper recommended in this writing-focused course.

    -   Oral exam: Your term paper draft will serve as the basis of the oral exam.

-   Seminar papers will be developed throughout the course

-   Submit until September 30st. (3.000 words)

# Course plan

## Overview

1.  General approaches (4 weeks)

    -   Weekly reading responses

    -   Develop research questions

2.  Studies & applications (5 weeks)

    -   Weekly reading responses

    -   Write first drafts

3.  Peer review (2 weeks)

4.  Seminar paper

# Course organization

-   Blackboard

    -   Session readings

    -   Upload of reading responses

    -   Submission of research questions, first drafts, and final papers

-   [Blackboard: POLSOZ_H\_30208_23S](https://fu-berlin.blackboard.com/webapps/blackboard/execute/content/file?cmd=view&content_id=_5422739_1&course_id=_182808_1&mode=view#_5422739_1 "Blackboard course")

# Questions?
